# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    import_email:
        class: AppBundle\Service\ImportService
        arguments: ["%kernel.root_dir%"]
